name: pdf-chatbot-with-vector-db-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py313h4f5f683_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - altair=5.5.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.0=h467f71e_16
  - aws-c-cal=0.9.2=hef2a5b8_1
  - aws-c-common=0.12.4=hfd05255_0
  - aws-c-compression=0.3.1=ha8a2810_6
  - aws-c-event-stream=0.5.5=h16d2062_1
  - aws-c-http=0.10.2=h909f643_3
  - aws-c-io=0.21.0=h20b9e97_1
  - aws-c-mqtt=0.13.1=h8a47558_4
  - aws-c-s3=0.8.3=hcc9d52c_1
  - aws-c-sdkutils=0.2.4=ha8a2810_1
  - aws-checksums=0.2.7=ha8a2810_2
  - aws-crt-cpp=0.32.10=h16ee0b7_3
  - aws-sdk-cpp=1.11.510=h41ea3a3_14
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.1.0=py313hfe59770_4
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cachetools=6.2.2=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py313h5ea7bf4_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh7428d3b_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.13.11=py313hd8ed1ab_100
  - cryptography=46.0.3=py313h392ebe0_0
  - cuda-cudart=12.9.79=he0c23c2_0
  - cuda-cudart_win-64=12.9.79=he0c23c2_0
  - cuda-cupti=12.9.79=hac47afa_1
  - cuda-nvrtc=12.9.86=hac47afa_1
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.2.21=h32ff316_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dataclasses-json=0.6.7=pyhd8ed1ab_1
  - datasets=4.0.0=pyhcf101f3_0
  - dill=0.3.8=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - filetype=1.2.0=pyhd8ed1ab_0
  - fpdf=1.7.2=pyhd8ed1ab_0
  - freetype=2.14.1=h57928b3_0
  - frozenlist=1.7.0=py313h0c48a3b_0
  - fsspec=2025.3.0=pyhd8ed1ab_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - google-ai-generativelanguage=0.6.15=pyhd8ed1ab_0
  - google-api-core=2.28.1=pyhd8ed1ab_0
  - google-api-python-client=2.187.0=pyh332efcf_0
  - google-auth=2.43.0=pyhd8ed1ab_0
  - google-auth-httplib2=0.2.1=pyhd8ed1ab_0
  - google-generativeai=0.8.5=pyh29332c3_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - greenlet=3.2.4=py313hfe59770_1
  - groq=0.37.1=pyhd8ed1ab_0
  - grpcio=1.71.0=py313h4c2d140_1
  - grpcio-tools=1.71.0=py313h5a86e1a_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.2.1=py310hfb9af98_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httplib2=0.31.0=pyhd8ed1ab_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - httpx-sse=0.4.3=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jiter=0.12.0=py313hf61f64f_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py313hfa70ccb_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - krb5=1.21.3=hdf4eb48_0
  - langchain=0.3.27=pymin313_h332efcf_1
  - langchain-community=0.3.31=pymin312_h332efcf_0
  - langchain-core=0.3.79=pyhd8ed1ab_0
  - langchain-google-genai=2.0.10=pyhd8ed1ab_0
  - langchain-groq=0.3.8=pyhd8ed1ab_0
  - langchain-huggingface=0.3.1=pyh4a576ae_0
  - langchain-openai=0.3.35=pyhd8ed1ab_0
  - langchain-qdrant=0.2.1=pyhd8ed1ab_0
  - langchain-text-splitters=0.3.11=pyhd8ed1ab_0
  - langgraph=1.0.1=pyhd8ed1ab_0
  - langgraph-checkpoint=3.0.1=pyhcf101f3_0
  - langgraph-prebuilt=1.0.1=pyhcf101f3_0
  - langgraph-sdk=0.2.9=pyhcf101f3_0
  - langsmith=0.3.45=pyhd8ed1ab_1
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250127.1=cxx17_h4eb7d71_0
  - libarrow=20.0.0=h7ea4809_8_cuda
  - libarrow-acero=20.0.0=h7d8d6a5_8_cuda
  - libarrow-dataset=20.0.0=h7d8d6a5_8_cuda
  - libarrow-substrait=20.0.0=hb76e781_8_cuda
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcublas=12.9.1.4=hac47afa_1
  - libcudnn=9.10.2.21=hca898b4_0
  - libcudnn-dev=9.10.2.21=hca898b4_0
  - libcudss=0.6.0.5=hca898b4_0
  - libcufft=11.4.1.4=hac47afa_1
  - libcurand=10.3.10.19=hac47afa_1
  - libcurl=8.17.0=h43ecb02_0
  - libcusolver=11.7.5.82=hac47afa_2
  - libcusparse=12.5.10.65=hac47afa_2
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libgomp=15.2.0=h1383e82_7
  - libgoogle-cloud=2.36.0=hf249c01_1
  - libgoogle-cloud-storage=2.36.0=he5eb982_1
  - libgrpc=1.71.0=h8c3449c_1
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmagma=2.9.0=hb6a17ea_3
  - libmpdec=4.0.0=h2466b09_0
  - libnvjitlink=12.9.86=hac47afa_2
  - libparquet=20.0.0=ha850022_8_cuda
  - libpng=1.6.50=h7351971_1
  - libprotobuf=5.29.3=hd33f5f0_2
  - libre2-11=2025.06.26=habfad5f_0
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.21.0=hbe90ef8_0
  - libtiff=4.7.1=h8f73337_1
  - libtorch=2.7.1=cuda128_mkl_hca3f899_302
  - libutf8proc=2.10.0=hff4702e_0
  - libuv=1.51.0=hfd05255_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h5d26750_0
  - libxml2-16=2.15.1=h692994f_0
  - libzlib=1.3.1=h2466b09_2
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.3=py313hd650c13_0
  - marshmallow=3.26.1=pyhd8ed1ab_0
  - mkl=2024.2.2=h57928b3_15
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py313hd650c13_0
  - multiprocess=0.70.16=py313ha7868ed_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - narwhals=2.12.0=pyhcf101f3_0
  - networkx=3.6=pyhcf101f3_0
  - numpy=2.3.5=py313hce7ae62_0
  - openai=1.109.1=pyhd8ed1ab_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - optree=0.18.0=py313hf069bd2_0
  - orc=2.1.2=h35764e3_0
  - orjson=3.11.4=py313hfbe8231_0
  - ormsgpack=1.12.0=py313h58076df_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313hc90dcd4_1
  - pillow=10.4.0=py313h24ec7aa_1
  - pip=25.3=pyh145f28c_0
  - portalocker=2.10.1=py313hfa70ccb_1
  - propcache=0.3.1=py313hb4c8b1a_0
  - proto-plus=1.26.1=pyhd8ed1ab_0
  - protobuf=5.29.3=py313h5813708_0
  - pthread-stubs=0.4=h0e40799_1002
  - pyarrow=20.0.0=py313hfa70ccb_0
  - pyarrow-core=20.0.0=py313h0d32010_0_cuda
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyh5e4992e_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.4=pyh3cfb1c2_0
  - pydantic-core=2.41.5=py313hfbe8231_1
  - pydantic-settings=2.12.0=pyh3cfb1c2_0
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pypdf2=3.0.1=pyhd8ed1ab_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.13.9=h09917c8_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-gil=3.13.11=h4df99d1_100
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py313hdf96bf3_1
  - python_abi=3.13=8_cp313
  - pytorch=2.7.1=cuda128_mkl_py313_h46e6c8c_302
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywin32=311=py313h40c08fc_1
  - pyyaml=6.0.3=py313hd650c13_0
  - qdrant-client=1.16.1=pyhd8ed1ab_0
  - re2=2025.06.26=h3dd2b4f_0
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2025.11.3=py313h5ea7bf4_1
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - rpds-py=0.29.0=py313hfbe8231_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - safetensors=0.7.0=py313hf61f64f_0
  - scikit-learn=1.7.2=py313he28f1d7_0
  - sentence-transformers=5.1.2=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h67fd636_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sqlalchemy=2.0.44=py313h5ea7bf4_0
  - streamlit=1.51.0=pyhd8ed1ab_1
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=hd094cb3_4
  - tenacity=9.1.2=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tiktoken=0.12.0=py313h034fbed_2
  - tk=8.6.13=h2c6b04d_3
  - tokenizers=0.22.2=py313h034fbed_0
  - toml=0.10.2=pyhd8ed1ab_2
  - tornado=6.5.2=py313h5ea7bf4_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.57.3=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_inspect=0.9.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - uritemplate=4.2.0=pyhd8ed1ab_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - watchdog=6.0.0=py313hfa70ccb_2
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xxhash=0.8.3=hbba6f48_0
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=py313hd650c13_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=h32d8bfd_0
  - zstandard=0.23.0=py313h5ea7bf4_3
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - pymupdf==1.26.7
      - scipy==1.16.3
prefix: pdf-chatbot-with-vector-db-rag
